server:
  port: 8081
spring:
  application:
    name: library
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  mail:
    username: email@gmail.com
    password: password
    host: smtp.gmail.com
    port: 587
    expiry-validity-in-seconds: 300
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  base64-secret: random
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 8640000
cors:
  client:
    url: http://localhost:4000
file:
  upload:
    base-uri: file:///D:/
